
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // --- HTML QUESTIONS (1-33) ---
  { id: 1, question: "რომელი ტეგით იწყება HTML5 დოკუმენტი?", options: ["<html>", "<!DOCTYPE html>", "<body>", "<head>"], correctAnswer: 1, category: 'HTML' },
  { id: 2, question: "რომელი ელემენტი გამოიყენება ყველაზე მაღალი დონის სათაურისთვის?", options: ["<h6>", "<head>", "<h1>", "<header>"], correctAnswer: 2, category: 'HTML' },
  { id: 3, question: "რას ნიშნავს ტეგი <p>?", options: ["სურათი", "აბზაცი", "ბმული", "ცხრილი"], correctAnswer: 1, category: 'HTML' },
  { id: 4, question: "რომელი ატრიბუტი გამოიყენება ბმულის (<a>) მისამართის მისათითებლად?", options: ["src", "link", "href", "target"], correctAnswer: 2, category: 'HTML' },
  { id: 5, question: "როგორ იწერება კომენტარი HTML-ში?", options: ["// კომენტარი", "/* კომენტარი */", "<!-- კომენტარი -->", "' კომენტარი"], correctAnswer: 2, category: 'HTML' },
  { id: 6, question: "რომელი ელემენტი გამოიყენება დაულაგებელი (unordered) სიის შესაქმნელად?", options: ["<ul>", "<ol>", "<li>", "<dl>"], correctAnswer: 0, category: 'HTML' },
  { id: 7, question: "რომელი ელემენტი გამოიყენება ცხრილის სტრიქონის შესაქმნელად?", options: ["<td>", "<th>", "<tr>", "<table>"], correctAnswer: 2, category: 'HTML' },
  { id: 8, question: "რომელი ატრიბუტით ვანიჭებთ უნიკალურ სახელს ელემენტს?", options: ["class", "id", "name", "style"], correctAnswer: 1, category: 'HTML' },
  { id: 9, question: "რას აკეთებს target='_blank' ატრიბუტი ბმულში?", options: ["ხსნის ბმულს იმავე ჩანართში", "ხსნის ბმულს ახალ ჩანართში", "ხურავს ბრაუზერს", "ბმულს ხდის უხილავს"], correctAnswer: 1, category: 'HTML' },
  { id: 10, question: "რომელი ელემენტი გამოიყენება ფორმის შესაქმნელად?", options: ["<input>", "<form>", "<select>", "<label>"], correctAnswer: 1, category: 'HTML' },
  { id: 11, question: "რომელი input type გამოიყენება პაროლის შესაყვანად?", options: ["type='text'", "type='hidden'", "type='password'", "type='secure'"], correctAnswer: 2, category: 'HTML' },
  { id: 12, question: "რომელი ელემენტი გამოიყენება სურათის ჩასასმელად?", options: ["<picture>", "<img>", "<figure>", "<canvas>"], correctAnswer: 1, category: 'HTML' },
  { id: 13, question: "რას ნიშნავს ატრიბუტი alt სურათის ტეგში?", options: ["სურათის ზომა", "სურათის ალტერნატიული ტექსტი", "სურათის ფერი", "სურათის სათაური"], correctAnswer: 1, category: 'HTML' },
  { id: 14, question: "რომელი ელემენტი გამოიყენება ნავიგაციის ზოლისთვის?", options: ["<nav>", "<header>", "<footer>", "<main>"], correctAnswer: 0, category: 'HTML' },
  { id: 15, question: "რომელი ტეგით შეგვიძლია ჩავსვათ ვიდეო გვერდზე?", options: ["<media>", "<movie>", "<video>", "<embed>"], correctAnswer: 2, category: 'HTML' },
  { id: 16, question: "რომელი ელემენტი აღნიშნავს გვერდის მთავარ კონტენტს?", options: ["<section>", "<article>", "<main>", "<div>"], correctAnswer: 2, category: 'HTML' },
  { id: 17, question: "რომელი ელემენტი გამოიყენება გვერდის ქვედა კოლონტიტულისთვის?", options: ["<bottom>", "<footer>", "<aside>", "<base>"], correctAnswer: 1, category: 'HTML' },
  { id: 18, question: "რას ნიშნავს <iframe>?", options: ["სურათის ჩარჩო", "ჩაშენებული ვებ-გვერდი (Inline Frame)", "გრაფიკული ელემენტი", "ტექსტის ბლოკი"], correctAnswer: 1, category: 'HTML' },
  { id: 19, question: "რომელი ელემენტი გამოიყენება პროგრესის ზოლის საჩვენებლად?", options: ["<bar>", "<meter>", "<progress>", "<range>"], correctAnswer: 2, category: 'HTML' },
  { id: 20, question: "რომელი ელემენტი გამოიყენება ფორმაში drop-down სიის შესაქმნელად?", options: ["<list>", "<input>", "<select>", "<option>"], correctAnswer: 2, category: 'HTML' },
  { id: 21, question: "რას ნიშნავს SVG?", options: ["Simple Video Graphics", "Scalable Vector Graphics", "Standard Visual Gaps", "Shadow Variable Grid"], correctAnswer: 1, category: 'HTML' },
  { id: 22, question: "რომელი ელემენტი გამოიყენება JavaScript-ის ჩასართავად HTML-ში?", options: ["<js>", "<script>", "<javascript>", "<link>"], correctAnswer: 1, category: 'HTML' },
  { id: 23, question: "რომელი ელემენტი გამოიყენება გარე CSS ფაილის დასაკავშირებლად?", options: ["<style>", "<link>", "<css>", "<href>"], correctAnswer: 1, category: 'HTML' },
  { id: 24, question: "რას ნიშნავს <br> ტეგი?", options: ["ტექსტის გაბოლდება", "ხაზის გაწყვეტა (Line Break)", "აბზაცის დასასრული", "ტექსტის ფერის შეცვლა"], correctAnswer: 1, category: 'HTML' },
  { id: 25, question: "რომელი ელემენტი გამოიყენება ტექსტის მცირე ინდექსის (subscript) საჩვენებლად?", options: ["<sup>", "<sub>", "<s>", "<small>"], correctAnswer: 1, category: 'HTML' },
  { id: 26, question: "რომელი ელემენტი გამოიყენება ტექსტის ზედა ინდექსის (superscript) საჩვენებლად?", options: ["<sup>", "<sub>", "<s>", "<big>"], correctAnswer: 0, category: 'HTML' },
  { id: 27, question: "რომელი ატრიბუტი განსაზღვრავს ენას <html> ტეგში?", options: ["lang", "language", "charset", "xml:lang"], correctAnswer: 0, category: 'HTML' },
  { id: 28, question: "რომელი ელემენტი გამოიყენება მოკლე ციტატისთვის?", options: ["<q>", "<blockquote>", "<cite>", "<citeq>"], correctAnswer: 0, category: 'HTML' },
  { id: 29, question: "რომელი ელემენტი გამოიყენება ფორმაში ღილაკის შესაქმნელად?", options: ["<press>", "<click>", "<button>", "<action>"], correctAnswer: 2, category: 'HTML' },
  { id: 30, question: "რას ნიშნავს <hr> ტეგი?", options: ["ჰორიზონტალური ხაზი", "მაღალი რეზოლუცია", "სათაურის ხაზი", "გრძელი აბზაცი"], correctAnswer: 0, category: 'HTML' },
  { id: 31, question: "რომელი input type გამოიყენება ფერის ასარჩევად?", options: ["type='color'", "type='palette'", "type='rgb'", "type='style'"], correctAnswer: 0, category: 'HTML' },
  { id: 32, question: "რომელი ატრიბუტით ვუთითებთ სურათის სიგანეს?", options: ["size", "width", "length", "scale"], correctAnswer: 1, category: 'HTML' },
  { id: 33, question: "რომელი ტეგით იწერება სათაური გვერდის ჩანართისთვის (tab)?", options: ["<header>", "<meta>", "<title>", "<head>"], correctAnswer: 2, category: 'HTML' },

  // --- CSS QUESTIONS (34-66) ---
  { id: 34, question: "რას ნიშნავს CSS?", options: ["Colorful Style Sheets", "Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets"], correctAnswer: 1, category: 'CSS' },
  { id: 35, question: "რომელი თვისება გამოიყენება ფონის ფერის შესაცვლელად?", options: ["color", "bg-color", "background-color", "background-fill"], correctAnswer: 2, category: 'CSS' },
  { id: 36, question: "რომელი თვისება გამოიყენება ტექსტის ფერის შესაცვლელად?", options: ["text-color", "color", "fg-color", "font-color"], correctAnswer: 1, category: 'CSS' },
  { id: 37, question: "რომელი თვისება განსაზღვრავს ტექსტის ზომას?", options: ["text-size", "font-weight", "font-size", "text-style"], correctAnswer: 2, category: 'CSS' },
  { id: 38, question: "რომელი სელექტორი გამოიყენება ელემენტის ასარჩევად მისი ID-ით?", options: [".", "#", "*", "@"], correctAnswer: 1, category: 'CSS' },
  { id: 39, question: "რომელი სელექტორი გამოიყენება ელემენტის ასარჩევად მისი კლასით?", options: [".", "#", "*", "&"], correctAnswer: 0, category: 'CSS' },
  { id: 40, question: "რომელი თვისება გამოიყენება ელემენტის შიდა დაშორებისთვის (padding)?", options: ["margin", "border", "padding", "spacing"], correctAnswer: 2, category: 'CSS' },
  { id: 41, question: "რომელი თვისება გამოიყენება ელემენტის გარე დაშორებისთვის (margin)?", options: ["margin", "padding", "border", "gap"], correctAnswer: 0, category: 'CSS' },
  { id: 42, question: "რომელი თვისება გამოიყენება ელემენტის საზღვრისთვის?", options: ["border", "outline", "stroke", "edge"], correctAnswer: 0, category: 'CSS' },
  { id: 43, question: "რომელი თვისება აკეთებს ტექსტს მუქად?", options: ["font-style", "font-weight: bold", "text-decoration", "text-bold"], correctAnswer: 1, category: 'CSS' },
  { id: 44, question: "რომელი თვისება გამოიყენება ტექსტის ხაზგასასმელად?", options: ["text-underline", "font-style", "text-decoration: underline", "line-through"], correctAnswer: 2, category: 'CSS' },
  { id: 45, question: "რომელი თვისება გამოიყენება Flexbox-ში ელემენტების ჰორიზონტალური გასწორებისთვის?", options: ["align-items", "justify-content", "flex-direction", "align-content"], correctAnswer: 1, category: 'CSS' },
  { id: 46, question: "რომელი თვისება გამოიყენება Flexbox-ში ელემენტების ვერტიკალური გასწორებისთვის?", options: ["justify-content", "align-items", "flex-wrap", "order"], correctAnswer: 1, category: 'CSS' },
  { id: 47, question: "რას აკეთებს box-sizing: border-box;?", options: ["ამატებს დამატებით ჩარჩოს", "ზომაში მოიცავს padding-ს და border-ს", "აცილებს მინდვრებს", "მხოლოდ შიდა ტექსტის ზომას ზღუდავს"], correctAnswer: 1, category: 'CSS' },
  { id: 48, question: "როგორ ავირჩიოთ ყველა <a> ელემენტი <div>-ის შიგნით?", options: ["div + a", "div > a", "div a", "div.a"], correctAnswer: 2, category: 'CSS' },
  { id: 49, question: "რომელი თვისება გამოიყენება ანიმაციის დროს ხანგრძლივობის მისათითებლად?", options: ["animation-delay", "animation-duration", "animation-speed", "animation-time"], correctAnswer: 1, category: 'CSS' },
  { id: 50, question: "რომელი მნიშვნელობა აქვს position თვისებას, რომ ელემენტი დარჩეს ეკრანის ერთ ადგილას სქროლის დროს?", options: ["relative", "absolute", "fixed", "static"], correctAnswer: 2, category: 'CSS' },
  { id: 51, question: "რა არის z-index თვისების დანიშნულება?", options: ["ზომის შეცვლა", "ელემენტების გადაფარვის რიგითობის მართვა", "ფერის ინტენსივობა", "ტექსტის დახრა"], correctAnswer: 1, category: 'CSS' },
  { id: 52, question: "რომელი თვისება გამოიყენება სვეტების რაოდენობის განსაზღვრისთვის?", options: ["column-count", "columns-num", "grid-cols", "display-cols"], correctAnswer: 0, category: 'CSS' },
  { id: 53, question: "როგორ იწერება მედია მოთხოვნა (media query)?", options: ["@query", "@screen", "@media", "@device"], correctAnswer: 2, category: 'CSS' },
  { id: 54, question: "რომელი თვისება გამოიყენება ელემენტის გამჭვირვალობისთვის?", options: ["transparency", "filter", "opacity", "visible"], correctAnswer: 2, category: 'CSS' },
  { id: 55, question: "რომელი ფუნქცია გამოიყენება დინამიური გამოთვლებისთვის CSS-ში?", options: ["sum()", "calc()", "eval()", "math()"], correctAnswer: 1, category: 'CSS' },
  { id: 56, question: "რომელი თვისება აბრუნებს ელემენტს?", options: ["rotate", "transform: rotate()", "spin", "turn"], correctAnswer: 1, category: 'CSS' },
  { id: 57, question: "რომელი თვისება გამოიყენება სიის მარკერების მოსაცილებლად?", options: ["list-style: none", "marker: hidden", "bullet: remove", "text-decoration: none"], correctAnswer: 0, category: 'CSS' },
  { id: 58, question: "რას ნიშნავს hover ფსევდო-კლასი?", options: ["ელემენტზე დაჭერას", "ელემენტზე მაუსის გადატარებას", "ელემენტის ფოკუსირებას", "ელემენტის ჩატვირთვას"], correctAnswer: 1, category: 'CSS' },
  { id: 59, question: "რომელი თვისება განსაზღვრავს შრიფტის ოჯახს?", options: ["font-style", "font-type", "font-family", "text-font"], correctAnswer: 2, category: 'CSS' },
  { id: 60, question: "რომელი თვისება გამოიყენება ჩრდილის დასამატებლად ტექსტზე?", options: ["box-shadow", "text-shadow", "shadow", "drop-shadow"], correctAnswer: 1, category: 'CSS' },
  { id: 61, question: "რომელი თვისება გამოიყენება ელემენტის ხილვადობის სამართავად?", options: ["visibility", "display", "Both A and B", "Neither"], correctAnswer: 2, category: 'CSS' },
  { id: 62, question: "რომელი თვისება გამოიყენება ელემენტებს შორის დაშორების შესაქმნელად Grid-ში?", options: ["grid-spacing", "gap", "grid-margin", "cell-padding"], correctAnswer: 1, category: 'CSS' },
  { id: 63, question: "რას ნიშნავს !important დეკლარაცია?", options: ["ხდის კოდს უფრო სწრაფს", "ანიჭებს წესს უპირატესობას (high priority)", "იყენებს მხოლოდ მობილურებზე", "ნიშნავს შეცდომას"], correctAnswer: 1, category: 'CSS' },
  { id: 64, question: "რომელი თვისება გამოიყენება კურსორის სტილის შესაცვლელად?", options: ["mouse", "cursor", "pointer", "icon"], correctAnswer: 1, category: 'CSS' },
  { id: 65, question: "რომელი თვისება განსაზღვრავს ელემენტის მაქსიმალურ სიგანეს?", options: ["max-width", "width-max", "limit-width", "bound-width"], correctAnswer: 0, category: 'CSS' },
  { id: 66, question: "როგორ განვსაზღვროთ CSS ცვლადი?", options: ["$variable", "--variable", "var-variable", "@variable"], correctAnswer: 1, category: 'CSS' },

  // --- JS QUESTIONS (67-100) ---
  { id: 67, question: "როგორ გამოვიტანოთ ტექსტი კონსოლში?", options: ["print()", "console.log()", "log.console()", "echo()"], correctAnswer: 1, category: 'JS' },
  { id: 68, question: "რომელი რეზერვირებული სიტყვა გამოიყენება ცვლადის გამოსაცხადებლად, რომლის მნიშვნელობაც არ იცვლება?", options: ["let", "var", "const", "fixed"], correctAnswer: 2, category: 'JS' },
  { id: 69, question: "რა ტიპის მონაცემია 'Hello'?", options: ["Number", "String", "Boolean", "Object"], correctAnswer: 1, category: 'JS' },
  { id: 70, question: "როგორ იწერება ფუნქცია JavaScript-ში?", options: ["function myFunction()", "func myFunction()", "def myFunction()", "new function()"], correctAnswer: 0, category: 'JS' },
  { id: 71, question: "როგორ გამოვიძახოთ ფუნქცია სახელით 'sayHello'?", options: ["call sayHello()", "sayHello()", "start sayHello()", "execute sayHello()"], correctAnswer: 1, category: 'JS' },
  { id: 72, question: "რას დააბრუნებს typeof 42?", options: ["'string'", "'boolean'", "'number'", "'object'"], correctAnswer: 2, category: 'JS' },
  { id: 73, question: "რომელი ოპერატორი გამოიყენება მნიშვნელობისა და ტიპის შესადარებლად (მკაცრი თანასწორობა)?", options: ["==", "=", "===", "!="], correctAnswer: 2, category: 'JS' },
  { id: 74, question: "რომელი ციკლი გამოიყენება მასივის ელემენტებზე გადასასვლელად?", options: ["for", "while", "do...while", "ყველა ჩამოთვლილი"], correctAnswer: 3, category: 'JS' },
  { id: 75, question: "რას ნიშნავს DOM?", options: ["Data Object Model", "Document Object Model", "Digital Order Model", "Desktop Object Management"], correctAnswer: 1, category: 'JS' },
  { id: 76, question: "რომელი მეთოდით ავირჩევთ ელემენტს მისი ID-ით?", options: ["document.selectById()", "document.getElementById()", "document.findId()", "document.queryId()"], correctAnswer: 1, category: 'JS' },
  { id: 77, question: "როგორ დავამატოთ 'click' მოვლენა ღილაკს?", options: ["button.addEvent('click')", "button.listen('click')", "button.addEventListener('click', ...)", "button.onClick(...)"], correctAnswer: 2, category: 'JS' },
  { id: 78, question: "როგორ შევქმნათ მასივი?", options: ["let colors = 'red', 'green'", "let colors = ['red', 'green']", "let colors = {red, green}", "let colors = (red, green)"], correctAnswer: 1, category: 'JS' },
  { id: 79, question: "როგორ გავიგოთ მასივის სიგრძე?", options: ["array.size()", "array.length", "array.count", "array.width"], correctAnswer: 1, category: 'JS' },
  { id: 80, question: "რომელი მეთოდი ამატებს ელემენტს მასივის ბოლოში?", options: ["pop()", "push()", "shift()", "unshift()"], correctAnswer: 1, category: 'JS' },
  { id: 81, question: "რას აკეთებს JSON.parse()?", options: ["ობიექტს გარდაქმნის სტრიქონად", "სტრიქონს გარდაქმნის ობიექტად", "შლის მონაცემებს", "აგზავნის მონაცემებს სერვერზე"], correctAnswer: 1, category: 'JS' },
  { id: 82, question: "რას აკეთებს JSON.stringify()?", options: ["სტრიქონს გარდაქმნის ობიექტად", "ობიექტს გარდაქმნის JSON სტრიქონად", "ამოწმებს შეცდომებს", "აფორმატებს ტექსტს"], correctAnswer: 1, category: 'JS' },
  { id: 83, question: "როგორ შევქმნათ ობიექტი?", options: ["let person = { name: 'John' }", "let person = [ name: 'John' ]", "let person = ( name: 'John' )", "let person = name = 'John'"], correctAnswer: 0, category: 'JS' },
  { id: 84, question: "რომელი ფუნქცია გამოიყენება ტაიმერის დასაყენებლად ერთჯერადად?", options: ["setInterval()", "setTimeout()", "setTimer()", "wait()"], correctAnswer: 1, category: 'JS' },
  { id: 85, question: "რას ნიშნავს NaN?", options: ["New and Null", "Not a Number", "Number and Null", "Next available Number"], correctAnswer: 1, category: 'JS' },
  { id: 86, question: "რომელი მეთოდით შეგვიძლია სტრიქონის ნაწილის ამოღება?", options: ["extract()", "slice()", "part()", "cut()"], correctAnswer: 1, category: 'JS' },
  { id: 87, question: "როგორ შევცვალოთ ელემენტის HTML კონტენტი?", options: ["element.text = '...'", "element.innerHTML = '...'", "element.html = '...'", "element.setContent('...')"], correctAnswer: 1, category: 'JS' },
  { id: 88, question: "რას დააბრუნებს Boolean(10 > 9)?", options: ["true", "false", "NaN", "undefined"], correctAnswer: 0, category: 'JS' },
  { id: 89, question: "როგორ შევქმნათ შემთხვევითი რიცხვი 0-დან 1-მდე?", options: ["Math.random()", "Math.rnd()", "random()", "Math.generate()"], correctAnswer: 0, category: 'JS' },
  { id: 90, question: "როგორ დავამრგვალოთ რიცხვი უახლოეს მთელამდე?", options: ["Math.round()", "Math.floor()", "Math.ceil()", "Math.trunc()"], correctAnswer: 0, category: 'JS' },
  { id: 91, question: "როგორ გადავაქციოთ სტრიქონი მთელ რიცხვად?", options: ["Integer()", "Number()", "parseInt()", "toFloat()"], correctAnswer: 2, category: 'JS' },
  { id: 92, question: "რას ნიშნავს 'this' რეზერვირებული სიტყვა?", options: ["მიმდინარე ფუნქციას", "მიმდინარე ობიექტს/კონტექსტს", "მშობელ ელემენტს", "გლობალურ ფანჯარას ყოველთვის"], correctAnswer: 1, category: 'JS' },
  { id: 93, question: "რომელი მეთოდით შეგვიძლია მასივიდან ელემენტების გაფილტვრა?", options: ["map()", "filter()", "reduce()", "search()"], correctAnswer: 1, category: 'JS' },
  { id: 94, question: "რომელი მეთოდით შეგვიძლია მასივის თითოეული ელემენტის გარდაქმნა?", options: ["map()", "foreach()", "transform()", "change()"], correctAnswer: 0, category: 'JS' },
  { id: 95, question: "რომელი მეთოდით შეგვიძლია მასივის ბოლო ელემენტის წაშლა?", options: ["pop()", "push()", "delete()", "shift()"], correctAnswer: 0, category: 'JS' },
  { id: 96, question: "რას დააბრუნებს 2 + '2'?", options: ["4", "22", "NaN", "Error"], correctAnswer: 1, category: 'JS' },
  { id: 97, question: "როგორ გამოვაცხადოთ Arrow Function?", options: ["let f = () => {}", "function f() => {}", "let f = function => {}", "f: () -> {}"], correctAnswer: 0, category: 'JS' },
  { id: 98, question: "რას ნიშნავს 'use strict'?", options: ["კოდის ოპტიმიზაციას", "მკაცრი რეჟიმის ჩართვას შეცდომების თავიდან ასაცილებლად", "ფაილის დაცვას", "გრაფიკულ რეჟიმს"], correctAnswer: 1, category: 'JS' },
  { id: 99, question: "როგორ შევამოწმოთ, არის თუ არა ცვლადი მასივი?", options: ["typeof variable === 'array'", "variable.isArray()", "Array.isArray(variable)", "is_array(variable)"], correctAnswer: 2, category: 'JS' },
  { id: 100, question: "რომელი ობიექტი გამოიყენება AJAX მოთხოვნისთვის (ძველი სტილით)?", options: ["XMLHttpRequest", "Fetch", "HttpRequest", "Axios"], correctAnswer: 0, category: 'JS' },
];
